id: P4B530174
initial_creation_type: input
source_metadata:
  title: Chögyal Pakpa Lodrö Gyaltsen
  language: en
  description: 'Texts by and about the great Sakya master Chögyal Pakpa Lodrö Gyaltsen
    (chos rgyal ’phags pa blo gros rgyal mtshan, 1235–1280):'
  volume:
    0baf61712fad4bddac3022a57a45d5be:
      title: Dhāraṇī of Goddess Parṇaśavarī
      parent: Dhāraṇī
    733c5891f1cf44a7ace88a5920f1f2a0:
      title: Short Maṇḍala Offering
      parent: Offering
    ac452d5602894b97876c6eb297cb4ba3:
      title: Thirty-Seven Point Maṇḍala Offering
      parent: Offering
    b9528535c5f04b788fb8cebcd9e2a100:
      title: Töpa Gyatsoma Offering Prayer
      parent: Offering
    7ade2be4ebd9423d8b4b60cc23bb4956:
      title: 'The Method of Accomplishment of Ārya Avalokiteśvara: The Practice of
        Great Compassion & Mahāmudrā in Union'
      parent: Sādhanas
created_at: '2022-02-28T22:43:55.172954'
last_modified_at: '2022-02-28T22:43:55.172961'
